{"uuid": "216554e2-4d2f-477f-a892-6012e5bdf9cd", "children": ["0d1ef9cb-6a68-472f-86b6-af90b0b50a4f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.167)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6EA7A4C25+3179557]\n\t(No symbol) [0x00007FF6EA4088A0]\n\t(No symbol) [0x00007FF6EA2991CA]\n\t(No symbol) [0x00007FF6EA271753]\n\t(No symbol) [0x00007FF6EA31F83E]\n\t(No symbol) [0x00007FF6EA33FBE2]\n\t(No symbol) [0x00007FF6EA317A03]\n\t(No symbol) [0x00007FF6EA2E06D0]\n\t(No symbol) [0x00007FF6EA2E1983]\n\tGetHandleVerifier [0x00007FF6EA8067CD+3579853]\n\tGetHandleVerifier [0x00007FF6EA81D1D2+3672530]\n\tGetHandleVerifier [0x00007FF6EA812153+3627347]\n\tGetHandleVerifier [0x00007FF6EA57092A+868650]\n\t(No symbol) [0x00007FF6EA412FFF]\n\t(No symbol) [0x00007FF6EA40F4A4]\n\t(No symbol) [0x00007FF6EA40F646]\n\t(No symbol) [0x00007FF6EA3FEAA9]\n\tBaseThreadInitThunk [0x00007FFAD6CBE8D7+23]\n\tRtlUserThreadStart [0x00007FFAD8D7BF6C+44]\n\n", "trace": "  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\97253\\Downloads\\SauceDemoAutomationProject\\tests\\conftest.py\", line 18, in setup\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 532, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\97253\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1743915022326, "stop": 1743915025975}], "start": 1743915022326, "stop": 1743915026657}